package com.youthen.master.service.dto;

// Generated 2015-4-20 10:12:30 by Hibernate Tools 3.2.2.GA

import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import com.youthen.master.persistence.entity.Company;
import com.youthen.master.persistence.entity.Kbn;

/**
 * MstCheckStandardItem generated by hbm2java
 */
public class MstCheckStandardDto extends MasterEntryDto {

    /**
     * 。
     */
    private static final long serialVersionUID = -2249035199828702265L;
    private Long id;
    private Long bigTypeId;
    private Kbn bigType;
    private Long smallTypeId;
    private Kbn smallType;
    private String standardName;
    private String standardCode;
    private String fileName;
    private String filePath;
    private String standardVersion;
    private Long status;
    private String createrId;
    private Long companyId;
    private Company company;
    private Date createTime;
    private String customizedCol;
    private String bakColumn1;
    private String bakColumn2;
    private String bakColumn3;
    private String bakColumn4;
    private String bakColumn5;
    private String bakColumn6;
    private String bakColumn7;
    private String bakColumn8;
    private String bakColumn9;
    private String bakColumn10;
    private String bakColumn11;
    private String bakColumn12;
    private String bakColumn13;
    private String bakColumn14;
    private String bakColumn15;
    private String bakColumn16;
    private String bakColumn17;
    private String bakColumn18;
    private String bakColumn19;
    private String bakColumn20;

    private List<File> uploadFileList;
    private List<String> uploadFileListContentType;
    private List<String> uploadFileListFileName;

    @Override
    public Long getId() {
        return this.id;
    }

    public void setId(final Long aId) {
        this.id = aId;
    }

    public Long getBigTypeId() {
        return this.bigTypeId;
    }

    public void setBigTypeId(final Long aBigTypeId) {
        this.bigTypeId = aBigTypeId;
    }

    public Long getSmallTypeId() {
        return this.smallTypeId;
    }

    public void setSmallTypeId(final Long aSmallTypeId) {
        this.smallTypeId = aSmallTypeId;
    }

    public String getStandardName() {
        return this.standardName;
    }

    public void setStandardName(final String aStandardName) {
        this.standardName = aStandardName;
    }

    public String getStandardCode() {
        return this.standardCode;
    }

    public void setStandardCode(final String aStandardCode) {
        this.standardCode = aStandardCode;
    }

    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(final String aFileName) {
        this.fileName = aFileName;
    }

    public String getFilePath() {
        return this.filePath;
    }

    public void setFilePath(final String aFilePath) {
        this.filePath = aFilePath;
    }

    public String getStandardVersion() {
        return this.standardVersion;
    }

    public void setStandardVersion(final String aStandardVersion) {
        this.standardVersion = aStandardVersion;
    }

    public Long getStatus() {
        return this.status;
    }

    public void setStatus(final Long aStatus) {
        this.status = aStatus;
    }

    public String getCreaterId() {
        return this.createrId;
    }

    public void setCreaterId(final String aCreaterId) {
        this.createrId = aCreaterId;
    }

    public Long getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(final Long aCompanyId) {
        this.companyId = aCompanyId;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(final Date aCreateTime) {
        this.createTime = aCreateTime;
    }

    public String getCustomizedCol() {
        return this.customizedCol;
    }

    public void setCustomizedCol(final String aCustomizedCol) {
        this.customizedCol = aCustomizedCol;
    }

    public String getBakColumn1() {
        return this.bakColumn1;
    }

    public void setBakColumn1(final String aBakColumn1) {
        this.bakColumn1 = aBakColumn1;
    }

    public String getBakColumn2() {
        return this.bakColumn2;
    }

    public void setBakColumn2(final String aBakColumn2) {
        this.bakColumn2 = aBakColumn2;
    }

    public String getBakColumn3() {
        return this.bakColumn3;
    }

    public void setBakColumn3(final String aBakColumn3) {
        this.bakColumn3 = aBakColumn3;
    }

    public String getBakColumn4() {
        return this.bakColumn4;
    }

    public void setBakColumn4(final String aBakColumn4) {
        this.bakColumn4 = aBakColumn4;
    }

    public String getBakColumn5() {
        return this.bakColumn5;
    }

    public void setBakColumn5(final String aBakColumn5) {
        this.bakColumn5 = aBakColumn5;
    }

    public String getBakColumn6() {
        return this.bakColumn6;
    }

    public void setBakColumn6(final String aBakColumn6) {
        this.bakColumn6 = aBakColumn6;
    }

    public String getBakColumn7() {
        return this.bakColumn7;
    }

    public void setBakColumn7(final String aBakColumn7) {
        this.bakColumn7 = aBakColumn7;
    }

    public String getBakColumn8() {
        return this.bakColumn8;
    }

    public void setBakColumn8(final String aBakColumn8) {
        this.bakColumn8 = aBakColumn8;
    }

    public String getBakColumn9() {
        return this.bakColumn9;
    }

    public void setBakColumn9(final String aBakColumn9) {
        this.bakColumn9 = aBakColumn9;
    }

    public String getBakColumn10() {
        return this.bakColumn10;
    }

    public void setBakColumn10(final String aBakColumn10) {
        this.bakColumn10 = aBakColumn10;
    }

    public String getBakColumn11() {
        return this.bakColumn11;
    }

    public void setBakColumn11(final String aBakColumn11) {
        this.bakColumn11 = aBakColumn11;
    }

    public String getBakColumn12() {
        return this.bakColumn12;
    }

    public void setBakColumn12(final String aBakColumn12) {
        this.bakColumn12 = aBakColumn12;
    }

    public String getBakColumn13() {
        return this.bakColumn13;
    }

    public void setBakColumn13(final String aBakColumn13) {
        this.bakColumn13 = aBakColumn13;
    }

    public String getBakColumn14() {
        return this.bakColumn14;
    }

    public void setBakColumn14(final String aBakColumn14) {
        this.bakColumn14 = aBakColumn14;
    }

    public String getBakColumn15() {
        return this.bakColumn15;
    }

    public void setBakColumn15(final String aBakColumn15) {
        this.bakColumn15 = aBakColumn15;
    }

    public String getBakColumn16() {
        return this.bakColumn16;
    }

    public void setBakColumn16(final String aBakColumn16) {
        this.bakColumn16 = aBakColumn16;
    }

    public String getBakColumn17() {
        return this.bakColumn17;
    }

    public void setBakColumn17(final String aBakColumn17) {
        this.bakColumn17 = aBakColumn17;
    }

    public String getBakColumn18() {
        return this.bakColumn18;
    }

    public void setBakColumn18(final String aBakColumn18) {
        this.bakColumn18 = aBakColumn18;
    }

    public String getBakColumn19() {
        return this.bakColumn19;
    }

    public void setBakColumn19(final String aBakColumn19) {
        this.bakColumn19 = aBakColumn19;
    }

    public String getBakColumn20() {
        return this.bakColumn20;
    }

    public void setBakColumn20(final String aBakColumn20) {
        this.bakColumn20 = aBakColumn20;
    }

    public Kbn getBigType() {
        return this.bigType;
    }

    public void setBigType(final Kbn aBigType) {
        this.bigType = aBigType;
    }

    public Kbn getSmallType() {
        return this.smallType;
    }

    public void setSmallType(final Kbn aSmallType) {
        this.smallType = aSmallType;
    }

    public Company getCompany() {
        return this.company;
    }

    public void setCompany(final Company aCompany) {
        this.company = aCompany;
    }

    public List<File> getUploadFileList() {
        return this.uploadFileList;
    }

    public void setUploadFileList(final ArrayList<File> aUploadFileList) {
        this.uploadFileList = aUploadFileList;
    }

    public void setUploadFileList(final List<File> aUploadFileList) {
        this.uploadFileList = aUploadFileList;
    }

    public List<String> getUploadFileListContentType() {
        return this.uploadFileListContentType;
    }

    public void setUploadFileListContentType(final List<String> aUploadFileListContentType) {
        this.uploadFileListContentType = aUploadFileListContentType;
    }

    public List<String> getUploadFileListFileName() {
        return this.uploadFileListFileName;
    }

    public void setUploadFileListFileName(final List<String> aUploadFileListFileName) {
        this.uploadFileListFileName = aUploadFileListFileName;
    }

}
